language: R

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3
  - sudo pip3 install --upgrade pip
  - sudo pip3 install pipenv

install:
  - make init

script:
  - make -j build
