language: python

python:
  - "3.6"

git:
  depth: 3
  lfs_skip_smudge: true

before_install:
  - scripts/ci.sh

env:
  global:
    - MAKEFLAGS="-j 2"

install:
  - make init

script:
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  on:
    branch: master
