language: python

python:
  - "3.6"

git:
  depth: 3
  lfs_skip_smudge: true

env:
  global:
    - MAKEFLAGS="-j 2"
    - YEONGHOEY_PANDOC_VER='2.2.1'
    - YEONGHOEY_PANDOC_DEB="pandoc-${YEONGHOEY_PANDOC_VER}-1-amd64.deb"

before_install:
  - pip install pipenv
  - wget "https://github.com/jgm/pandoc/releases/download/${YEONGHOEY_PANDOC_VER}/${YEONGHOEY_PANDOC_DEB}"
  - sudo dpkg -i "${YHY_PANDOC_DEB}"

install:
  - make ci

script:
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  on:
    branch: master
