language: python

python:
  - "3.6"

git:
  depth: 3
  lfs_skip_smudge: true

env:
  global:
    - PANDOC_VERSION='2.2.1'
    - PANDOC_DEB="pandoc-${PANDOC_VERSION}-1-amd64.deb"
    - PANDOC_URL="https://github.com/jgm/pandoc/releases/download/${PANDOC_VERSION}/${PANDOC_DEB}"
    - MAKEFLAGS="-j 2"

before_install:
  - pip install pipenv
  - wget "${PANDOC_URL}"
  - sudo dpkg -i "${PANDOC_DEB}"

install:
  - make init

script:
  - make build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  on:
    branch: master
