language: python

python:
  - "3.6"

git:
  depth: 3

before_install:
  - wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-2.2.1-1-amd64.deb
  - pip install pipenv

install:
  - make init

script:
  - make -j4 build

cache:
  directories:
    - _site

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _site
  on:
    branch: master
